env:
  browser: true
  es2021: true
  node: true

extends:
  - eslint:recommended
  - plugin:vue/essential
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    modules: true
    jsx: true
plugins:
  - vue
rules:
  vue/no-multiple-template-root: off
  quotes: [error, single, { avoidEscape: true }]
  indent: [error, 2]
  no-unused-vars: off
  no-unreachable: off
  no-console: off
